/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as EventSlugIndexRouteImport } from './routes/event.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as EventSlugVoiceRouteImport } from './routes/event.$slug.voice'
import { Route as EventSlugNotesRouteImport } from './routes/event.$slug.notes'
import { Route as EventSlugCaptureRouteImport } from './routes/event.$slug.capture'
import { Route as EventSlugAlbumRouteImport } from './routes/event.$slug.album'
import { Route as AuthenticatedDashboardCreateRouteImport } from './routes/_authenticated.dashboard.create'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated.admin.templates'
import { Route as AuthenticatedAdminPrintRouteImport } from './routes/_authenticated.admin.print'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated.admin.media'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated.admin.homepage'
import { Route as AuthenticatedAdminGuestsRouteImport } from './routes/_authenticated.admin.guests'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated.admin.events'
import { Route as AuthenticatedAdminEventsIndexRouteImport } from './routes/_authenticated.admin.events.index'
import { Route as AuthenticatedDashboardEventIdRouteImport } from './routes/_authenticated.dashboard.event.$id'
import { Route as AuthenticatedAdminPagesPricingRouteImport } from './routes/_authenticated.admin.pages.pricing'
import { Route as AuthenticatedAdminPagesHowItWorksRouteImport } from './routes/_authenticated.admin.pages.how-it-works'
import { Route as AuthenticatedAdminPagesCreateEventFormRouteImport } from './routes/_authenticated.admin.pages.create-event-form'
import { Route as AuthenticatedAdminPagesAboutRouteImport } from './routes/_authenticated.admin.pages.about'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated.admin.events.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventSlugIndexRoute = EventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const EventSlugVoiceRoute = EventSlugVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => EventSlugRoute,
} as any)
const EventSlugNotesRoute = EventSlugNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => EventSlugRoute,
} as any)
const EventSlugCaptureRoute = EventSlugCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => EventSlugRoute,
} as any)
const EventSlugAlbumRoute = EventSlugAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => EventSlugRoute,
} as any)
const AuthenticatedDashboardCreateRoute =
  AuthenticatedDashboardCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrintRoute = AuthenticatedAdminPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuestsRoute =
  AuthenticatedAdminGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIndexRoute =
  AuthenticatedAdminEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)
const AuthenticatedDashboardEventIdRoute =
  AuthenticatedDashboardEventIdRouteImport.update({
    id: '/event/$id',
    path: '/event/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminPagesPricingRoute =
  AuthenticatedAdminPagesPricingRouteImport.update({
    id: '/pages/pricing',
    path: '/pages/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesHowItWorksRoute =
  AuthenticatedAdminPagesHowItWorksRouteImport.update({
    id: '/pages/how-it-works',
    path: '/pages/how-it-works',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesCreateEventFormRoute =
  AuthenticatedAdminPagesCreateEventFormRouteImport.update({
    id: '/pages/create-event-form',
    path: '/pages/create-event-form',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesAboutRoute =
  AuthenticatedAdminPagesAboutRouteImport.update({
    id: '/pages/about',
    path: '/pages/about',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/event/$slug': typeof EventSlugRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/print': typeof AuthenticatedAdminPrintRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/dashboard/create': typeof AuthenticatedDashboardCreateRoute
  '/event/$slug/album': typeof EventSlugAlbumRoute
  '/event/$slug/capture': typeof EventSlugCaptureRoute
  '/event/$slug/notes': typeof EventSlugNotesRoute
  '/event/$slug/voice': typeof EventSlugVoiceRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/event/$slug/': typeof EventSlugIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/pages/about': typeof AuthenticatedAdminPagesAboutRoute
  '/admin/pages/create-event-form': typeof AuthenticatedAdminPagesCreateEventFormRoute
  '/admin/pages/how-it-works': typeof AuthenticatedAdminPagesHowItWorksRoute
  '/admin/pages/pricing': typeof AuthenticatedAdminPagesPricingRoute
  '/dashboard/event/$id': typeof AuthenticatedDashboardEventIdRoute
  '/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/print': typeof AuthenticatedAdminPrintRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/dashboard/create': typeof AuthenticatedDashboardCreateRoute
  '/event/$slug/album': typeof EventSlugAlbumRoute
  '/event/$slug/capture': typeof EventSlugCaptureRoute
  '/event/$slug/notes': typeof EventSlugNotesRoute
  '/event/$slug/voice': typeof EventSlugVoiceRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/event/$slug': typeof EventSlugIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/pages/about': typeof AuthenticatedAdminPagesAboutRoute
  '/admin/pages/create-event-form': typeof AuthenticatedAdminPagesCreateEventFormRoute
  '/admin/pages/how-it-works': typeof AuthenticatedAdminPagesHowItWorksRoute
  '/admin/pages/pricing': typeof AuthenticatedAdminPagesPricingRoute
  '/dashboard/event/$id': typeof AuthenticatedDashboardEventIdRoute
  '/admin/events': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/event/$slug': typeof EventSlugRouteWithChildren
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/_authenticated/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/print': typeof AuthenticatedAdminPrintRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/dashboard/create': typeof AuthenticatedDashboardCreateRoute
  '/event/$slug/album': typeof EventSlugAlbumRoute
  '/event/$slug/capture': typeof EventSlugCaptureRoute
  '/event/$slug/notes': typeof EventSlugNotesRoute
  '/event/$slug/voice': typeof EventSlugVoiceRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/event/$slug/': typeof EventSlugIndexRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_authenticated/admin/pages/about': typeof AuthenticatedAdminPagesAboutRoute
  '/_authenticated/admin/pages/create-event-form': typeof AuthenticatedAdminPagesCreateEventFormRoute
  '/_authenticated/admin/pages/how-it-works': typeof AuthenticatedAdminPagesHowItWorksRoute
  '/_authenticated/admin/pages/pricing': typeof AuthenticatedAdminPagesPricingRoute
  '/_authenticated/dashboard/event/$id': typeof AuthenticatedDashboardEventIdRoute
  '/_authenticated/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/event/$slug'
    | '/admin/events'
    | '/admin/guests'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/print'
    | '/admin/templates'
    | '/dashboard/create'
    | '/event/$slug/album'
    | '/event/$slug/capture'
    | '/event/$slug/notes'
    | '/event/$slug/voice'
    | '/admin/'
    | '/dashboard/'
    | '/event/$slug/'
    | '/admin/events/$id'
    | '/admin/pages/about'
    | '/admin/pages/create-event-form'
    | '/admin/pages/how-it-works'
    | '/admin/pages/pricing'
    | '/dashboard/event/$id'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/admin/guests'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/print'
    | '/admin/templates'
    | '/dashboard/create'
    | '/event/$slug/album'
    | '/event/$slug/capture'
    | '/event/$slug/notes'
    | '/event/$slug/voice'
    | '/admin'
    | '/dashboard'
    | '/event/$slug'
    | '/admin/events/$id'
    | '/admin/pages/about'
    | '/admin/pages/create-event-form'
    | '/admin/pages/how-it-works'
    | '/admin/pages/pricing'
    | '/dashboard/event/$id'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/event/$slug'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/guests'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/print'
    | '/_authenticated/admin/templates'
    | '/_authenticated/dashboard/create'
    | '/event/$slug/album'
    | '/event/$slug/capture'
    | '/event/$slug/notes'
    | '/event/$slug/voice'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/event/$slug/'
    | '/_authenticated/admin/events/$id'
    | '/_authenticated/admin/pages/about'
    | '/_authenticated/admin/pages/create-event-form'
    | '/_authenticated/admin/pages/how-it-works'
    | '/_authenticated/admin/pages/pricing'
    | '/_authenticated/dashboard/event/$id'
    | '/_authenticated/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  EventSlugRoute: typeof EventSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/event/$slug/': {
      id: '/event/$slug/'
      path: '/'
      fullPath: '/event/$slug/'
      preLoaderRoute: typeof EventSlugIndexRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/event/$slug/voice': {
      id: '/event/$slug/voice'
      path: '/voice'
      fullPath: '/event/$slug/voice'
      preLoaderRoute: typeof EventSlugVoiceRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/event/$slug/notes': {
      id: '/event/$slug/notes'
      path: '/notes'
      fullPath: '/event/$slug/notes'
      preLoaderRoute: typeof EventSlugNotesRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/event/$slug/capture': {
      id: '/event/$slug/capture'
      path: '/capture'
      fullPath: '/event/$slug/capture'
      preLoaderRoute: typeof EventSlugCaptureRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/event/$slug/album': {
      id: '/event/$slug/album'
      path: '/album'
      fullPath: '/event/$slug/album'
      preLoaderRoute: typeof EventSlugAlbumRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/_authenticated/dashboard/create': {
      id: '/_authenticated/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof AuthenticatedDashboardCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/print': {
      id: '/_authenticated/admin/print'
      path: '/print'
      fullPath: '/admin/print'
      preLoaderRoute: typeof AuthenticatedAdminPrintRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guests': {
      id: '/_authenticated/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AuthenticatedAdminGuestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/': {
      id: '/_authenticated/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AuthenticatedAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
    '/_authenticated/dashboard/event/$id': {
      id: '/_authenticated/dashboard/event/$id'
      path: '/event/$id'
      fullPath: '/dashboard/event/$id'
      preLoaderRoute: typeof AuthenticatedDashboardEventIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/pages/pricing': {
      id: '/_authenticated/admin/pages/pricing'
      path: '/pages/pricing'
      fullPath: '/admin/pages/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPagesPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/how-it-works': {
      id: '/_authenticated/admin/pages/how-it-works'
      path: '/pages/how-it-works'
      fullPath: '/admin/pages/how-it-works'
      preLoaderRoute: typeof AuthenticatedAdminPagesHowItWorksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/create-event-form': {
      id: '/_authenticated/admin/pages/create-event-form'
      path: '/pages/create-event-form'
      fullPath: '/admin/pages/create-event-form'
      preLoaderRoute: typeof AuthenticatedAdminPagesCreateEventFormRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/about': {
      id: '/_authenticated/admin/pages/about'
      path: '/pages/about'
      fullPath: '/admin/pages/about'
      preLoaderRoute: typeof AuthenticatedAdminPagesAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
  }
}

interface AuthenticatedAdminEventsRouteChildren {
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminEventsIndexRoute: typeof AuthenticatedAdminEventsIndexRoute
}

const AuthenticatedAdminEventsRouteChildren: AuthenticatedAdminEventsRouteChildren =
  {
    AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
    AuthenticatedAdminEventsIndexRoute: AuthenticatedAdminEventsIndexRoute,
  }

const AuthenticatedAdminEventsRouteWithChildren =
  AuthenticatedAdminEventsRoute._addFileChildren(
    AuthenticatedAdminEventsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRouteWithChildren
  AuthenticatedAdminGuestsRoute: typeof AuthenticatedAdminGuestsRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPrintRoute: typeof AuthenticatedAdminPrintRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPagesAboutRoute: typeof AuthenticatedAdminPagesAboutRoute
  AuthenticatedAdminPagesCreateEventFormRoute: typeof AuthenticatedAdminPagesCreateEventFormRoute
  AuthenticatedAdminPagesHowItWorksRoute: typeof AuthenticatedAdminPagesHowItWorksRoute
  AuthenticatedAdminPagesPricingRoute: typeof AuthenticatedAdminPagesPricingRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRouteWithChildren,
  AuthenticatedAdminGuestsRoute: AuthenticatedAdminGuestsRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPrintRoute: AuthenticatedAdminPrintRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPagesAboutRoute: AuthenticatedAdminPagesAboutRoute,
  AuthenticatedAdminPagesCreateEventFormRoute:
    AuthenticatedAdminPagesCreateEventFormRoute,
  AuthenticatedAdminPagesHowItWorksRoute:
    AuthenticatedAdminPagesHowItWorksRoute,
  AuthenticatedAdminPagesPricingRoute: AuthenticatedAdminPagesPricingRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCreateRoute: typeof AuthenticatedDashboardCreateRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardEventIdRoute: typeof AuthenticatedDashboardEventIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCreateRoute: AuthenticatedDashboardCreateRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardEventIdRoute: AuthenticatedDashboardEventIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EventSlugRouteChildren {
  EventSlugAlbumRoute: typeof EventSlugAlbumRoute
  EventSlugCaptureRoute: typeof EventSlugCaptureRoute
  EventSlugNotesRoute: typeof EventSlugNotesRoute
  EventSlugVoiceRoute: typeof EventSlugVoiceRoute
  EventSlugIndexRoute: typeof EventSlugIndexRoute
}

const EventSlugRouteChildren: EventSlugRouteChildren = {
  EventSlugAlbumRoute: EventSlugAlbumRoute,
  EventSlugCaptureRoute: EventSlugCaptureRoute,
  EventSlugNotesRoute: EventSlugNotesRoute,
  EventSlugVoiceRoute: EventSlugVoiceRoute,
  EventSlugIndexRoute: EventSlugIndexRoute,
}

const EventSlugRouteWithChildren = EventSlugRoute._addFileChildren(
  EventSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  EventSlugRoute: EventSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
